//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cerere_Donare
    {
        public string id_cerere { get; set; }
        public string status { get; set; }
        public string grupa_sanguina { get; set; }
        public bool trombocite { get; set; }
        public bool globule_rosii { get; set; }
        public bool plasma { get; set; }
        public int id_medic { get; set; }
        public string nume_pacient { get; set; }
    }
}
