//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chestionar_Medical
    {
        public Chestionar_Medical()
        {
            this.Donators = new HashSet<Donator>();
        }
    
        public int id_chestionar { get; set; }
        public int greutate { get; set; }
        public int puls { get; set; }
        public string tensiune { get; set; }
        public bool interventii_chirurgicale_recente { get; set; }
        public bool sarcina { get; set; }
        public bool consum_grasimi { get; set; }
        public bool tratament { get; set; }
        public bool alte_boli { get; set; }
    
        public virtual ICollection<Donator> Donators { get; set; }
    }
}
