//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chestionar_Medical
    {
        public int id_chestionar { get; set; }
        public string greutate { get; set; }
        public string puls { get; set; }
        public string tensiune { get; set; }
        public bool interventii_chirurgicale_recente { get; set; }
        public bool sarcina { get; set; }
        public bool consum_grasimi { get; set; }
        public bool tratament { get; set; }
        public string alte_boli { get; set; }
        public bool aprobat { get; set; }
        public string cnp_donator { get; set; }
    
        public virtual Donator Donator { get; set; }
    }
}
