//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Componente_Punga
    {
        public int id_punga { get; set; }
        public bool trombocite { get; set; }
        public bool globule_rosii { get; set; }
        public bool plasma { get; set; }
    
        public virtual Punga_Sange Punga_Sange { get; set; }
    }
}
