//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_Recoltare
    {
        public Personal_Recoltare()
        {
            this.Punga_Sange = new HashSet<Punga_Sange>();
        }
    
        public int id_personal { get; set; }
        public string nume { get; set; }
        public string email { get; set; }
        public int id_cont { get; set; }
    
        public virtual Cont Cont { get; set; }
        public virtual ICollection<Punga_Sange> Punga_Sange { get; set; }
    }
}
