//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punga_Sange
    {
        public int id_punga { get; set; }
        public System.DateTime data { get; set; }
        public string grupa_sanguina { get; set; }
        public string cnp_donator { get; set; }
        public int id_personal { get; set; }
    
        public virtual Componente_Punga Componente_Punga { get; set; }
        public virtual Donator Donator { get; set; }
        public virtual Personal_Recoltare Personal_Recoltare { get; set; }
    }
}
