//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spital
    {
        public Spital()
        {
            this.Medics = new HashSet<Medic>();
            this.Pacients = new HashSet<Pacient>();
        }
    
        public int id_spital { get; set; }
        public string denumire { get; set; }
        public string judet { get; set; }
    
        public virtual ICollection<Medic> Medics { get; set; }
        public virtual ICollection<Pacient> Pacients { get; set; }
    }
}
